-- magnitude
--------------------------------------------------
-- find total customer by countries
select country , count(distinct customer_key) as total_customers
from customers
group by country;
-- find total product by categories
select category, count(product_key)
from products
group by category;
-- what is the total revenue gerarated for each categoreis 
select category, sum(sales_amount) as total_revenue
from products p left join sales s
on p.product_key = s.product_key
group by category;
-- what is the avg cost in each categories
select category, count(cost) as average_cost
from products
group by category
order by average_cost desc;

-- find total revienue is generated by  each cutomers 

select c.customer_key, c.first_name,sum(s.sales_amount) as total_paisa
from customers c left join sales s
on c.customer_key = s.customer_key
group by c.customer_key,c.first_name
order by total_paisa desc;


-- what is the distribution  of sold item across countries 
select c.country,sum(s.quantity) as total_paisa
from customers c left join sales s
on c.customer_key = s.customer_key
group by country
order by total_paisa desc


